apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
spec:
  selector:
    matchLabels:
      name: sample
  replicas: 2
  template:
    metadata:
      labels:
        name: sample
    spec:
      containers:
      - name: sample-ctr
        imagePullPolicy: Never
        image: nginx:latest
        ports:
        - containerPort: 80
